import {StyleSheet} from 'react-native';

module.exports = StyleSheet.create({
  card: {
    flex: 1,
    margin: 8,
    padding: 16,
    backgroundColor: 'lightgray',
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 5,
  },
  card_out: {
    height: 130,
    padding: 10,
    backgroundColor: 'whitesmoke',
    width: 300,
    flex: 1,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'start',
    gap: 10,
    marginRight: 20,
    borderRadius: 16,
  },
  card_in: {
    height: 100,
    width: 80,
    flex: 0,
    backgroundColor: '#BA1A4C',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
  },
  card_hold: {
    color: 'white',
    fontWeight: 700,
    fontSize: 18,
  },
  card_text: {
    flex: 1,
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    height: 100,
    padding: 10,
  },
  font_text: {
    fontSize: 16,
    fontWeight: 600,
    color: 'gray',
  },
  font_bold: {
    fontSize: 18,
    fontWeight: 600,
  },
  list_card: {
    height: 200,
    backgroundColor: 'whitesmoke',
    flex: 1,
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    flexDirection: 'column',
    gap: 10,
    paddingVertical: 10,
    paddingHorizontal: 10,
    marginVertical: 5,
    marginHorizontal: 5,
    borderRadius: 16,
  },
  list_card_in: {
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    flexDirection: 'row',
    gap: 10,
  },
  list_card_box: {
    height: 90,
    flex: 0,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#BA1A4C',
    width: 100,
    borderRadius: 16,
  },
  list_card_text_b: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 18,
  },
  list_card_btn: {
    flex: 1,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
  },
  list_card_white_btn: {
    backgroundColor: 'white',
    borderColor: '#376095',
    borderWidth: 1,
  },
});
